#!/usr/bin/env bash
set -euo pipefail

# Docker/Linux friendly installer for this dotfiles repo.
# The original install.sh is macOS/Homebrew oriented. This script avoids root/sudo
# and installs the small set of tools needed by this Docker environment under
# /opt/data by default.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="${DATA_DIR:-/opt/data}"
HOME_DIR="${HOME_DIR:-$DATA_DIR/home}"
PREFIX="${PREFIX:-$DATA_DIR/local}"
BIN_DIR="${BIN_DIR:-$DATA_DIR/bin}"
TMP_DIR="${TMP_DIR:-$DATA_DIR/.local/tmp-docker-install}"

mkdir -p "$HOME_DIR" "$PREFIX" "$BIN_DIR" "$TMP_DIR"
export PATH="$BIN_DIR:$HOME_DIR/bin:$PATH"

log() {
  printf '==> %s\n' "$*"
}

warn() {
  printf 'WARN: %s\n' "$*" >&2
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1
}

machine_arch() {
  case "$(uname -m)" in
    x86_64|amd64) printf 'amd64' ;;
    aarch64|arm64) printf 'arm64' ;;
    *)
      printf 'Unsupported architecture: %s\n' "$(uname -m)" >&2
      exit 1
      ;;
  esac
}

latest_github_version() {
  local repo="$1"
  curl -fsSL "https://api.github.com/repos/${repo}/releases/latest" \
    | python3 -c 'import sys,json; print(json.load(sys.stdin)["tag_name"].lstrip("v"))'
}

install_gh() {
  if need_cmd gh; then
    log "gh already available: $(command -v gh)"
    return
  fi

  local arch version asset url work
  arch="$(machine_arch)"
  version="$(latest_github_version cli/cli)"
  asset="gh_${version}_linux_${arch}.tar.gz"
  url="https://github.com/cli/cli/releases/download/v${version}/${asset}"
  work="$TMP_DIR/gh"

  log "Installing gh ${version} to ${BIN_DIR}"
  rm -rf "$work"
  mkdir -p "$work"
  curl -fL --retry 3 -o "$work/$asset" "$url"
  tar -xzf "$work/$asset" -C "$work"
  cp "$work/gh_${version}_linux_${arch}/bin/gh" "$BIN_DIR/gh"
  chmod +x "$BIN_DIR/gh"
}

install_starship() {
  if need_cmd starship; then
    log "starship already available: $(command -v starship)"
    return
  fi

  local arch target version asset url work
  arch="$(machine_arch)"
  case "$arch" in
    amd64) target="x86_64-unknown-linux-gnu" ;;
    arm64) target="aarch64-unknown-linux-musl" ;;
  esac
  version="$(latest_github_version starship/starship)"
  asset="starship-${target}.tar.gz"
  url="https://github.com/starship/starship/releases/download/v${version}/${asset}"
  work="$TMP_DIR/starship"

  log "Installing starship ${version} to ${BIN_DIR}"
  rm -rf "$work"
  mkdir -p "$work"
  curl -fL --retry 3 -o "$work/$asset" "$url"
  tar -xzf "$work/$asset" -C "$work"
  cp "$work/starship" "$BIN_DIR/starship"
  chmod +x "$BIN_DIR/starship"
}

install_zsh_userland() {
  if [ -x "$BIN_DIR/zsh" ] && "$BIN_DIR/zsh" -c 'zmodload zsh/zle' >/dev/null 2>&1; then
    log "zsh already available: $BIN_DIR/zsh"
    return
  fi

  if ! need_cmd apt-get || ! need_cmd dpkg-deb; then
    warn "apt-get/dpkg-deb not found; skipping userland zsh install"
    return
  fi

  log "Installing zsh under ${PREFIX} without sudo"
  local work
  work="$TMP_DIR/zsh"
  rm -rf "$work"
  mkdir -p "$work"
  (
    cd "$work"
    apt-get download zsh zsh-common
    for deb in zsh-common_*.deb zsh_*.deb; do
      dpkg-deb -x "$deb" "$PREFIX"
    done
  )

  cat > "$BIN_DIR/zsh" <<EOF
#!/bin/sh
export ZDOTDIR="$HOME_DIR"
export PATH="$BIN_DIR:$HOME_DIR/bin:\$PATH"
exec "$PREFIX/usr/bin/zsh" "\$@"
EOF
  chmod +x "$BIN_DIR/zsh"
}

backup_path() {
  local path="$1"
  if [ -e "$path" ] && [ ! -L "$path" ]; then
    local backup="${path}.dotbackup.$(date +%Y%m%d%H%M%S)"
    log "Backing up $path to $backup"
    mv "$path" "$backup"
  fi
}

link_file() {
  local src="$1"
  local dest="$2"

  if [ ! -e "$src" ]; then
    warn "Missing source: $src"
    return
  fi

  mkdir -p "$(dirname "$dest")"
  backup_path "$dest"
  rm -rf "$dest"
  ln -s "$src" "$dest"
  log "Linked $dest -> $src"
}

write_docker_shell_bootstrap() {
  log "Writing Docker shell bootstrap: $DATA_DIR/env.sh"
  cat > "$DATA_DIR/env.sh" <<EOF
# Source this after Docker restart to expose userland tools installed under ${DATA_DIR}.
export PATH="${BIN_DIR}:${HOME_DIR}/bin:\$PATH"
export ZDOTDIR="${HOME_DIR}"
EOF

  log "Writing Docker profile bootstrap: $HOME_DIR/.profile"
  cat > "$HOME_DIR/.profile" <<EOF
# Generated by install_for_docker.sh.
. "$DATA_DIR/env.sh"
EOF

  log "Writing Docker zsh bootstrap: $HOME_DIR/.zshenv"
  cat > "$HOME_DIR/.zshenv" <<EOF
# Generated by install_for_docker.sh.
# Userland zsh is installed under ${PREFIX}; make modules/functions discoverable.
module_path=(${PREFIX}/usr/lib/aarch64-linux-gnu/zsh/5.9 ${PREFIX}/usr/lib/x86_64-linux-gnu/zsh/5.9 \$module_path)
fpath=(${PREFIX}/usr/share/zsh/functions/* \$fpath)
export PATH="${BIN_DIR}:${HOME_DIR}/bin:\$PATH"
EOF
}

maybe_set_default_shell() {
  if [ "${SET_DEFAULT_SHELL:-0}" != "1" ]; then
    return
  fi

  local shell_path="${DEFAULT_SHELL_PATH:-$BIN_DIR/zsh}"
  local target_user="${DEFAULT_SHELL_USER:-${USER:-root}}"

  if [ "$(id -u)" != "0" ]; then
    warn "SET_DEFAULT_SHELL=1 requested, but current user is not root; run as root to change login shell"
    return
  fi

  if [ ! -x "$shell_path" ]; then
    warn "Default shell path is not executable: $shell_path"
    return
  fi

  if [ -w /etc/shells ] && ! grep -qxF "$shell_path" /etc/shells; then
    log "Adding $shell_path to /etc/shells"
    printf '%s\n' "$shell_path" >> /etc/shells
  fi

  if command -v chsh >/dev/null 2>&1; then
    log "Setting default shell for $target_user to $shell_path"
    chsh -s "$shell_path" "$target_user"
  else
    warn "chsh not found; edit /etc/passwd manually or install passwd utilities"
  fi
}

install_tpm() {
  if ! need_cmd git; then
    warn "git not found; skipping tmux plugin manager"
    return
  fi

  local tpm_dir="$HOME_DIR/.tmux/plugins/tpm"
  if [ -d "$tpm_dir" ]; then
    log "tpm already installed: $tpm_dir"
    return
  fi

  log "Installing tmux plugin manager"
  git clone https://github.com/tmux-plugins/tpm "$tpm_dir" || warn "tpm clone failed"
}

link_dotfiles() {
  link_file "$SCRIPT_DIR/.zshrc" "$HOME_DIR/.zshrc"
  link_file "$SCRIPT_DIR/starship.toml" "$HOME_DIR/.config/starship.toml"
  link_file "$SCRIPT_DIR/.tmux.conf" "$HOME_DIR/.tmux.conf"
  link_file "$SCRIPT_DIR/ccstatusline.json" "$HOME_DIR/.config/ccstatusline/settings.json"
  link_file "$SCRIPT_DIR/agent/CLAUDE.md" "$HOME_DIR/.claude/CLAUDE.md"
  link_file "$SCRIPT_DIR/agent/AGENTS.md" "$HOME_DIR/.codex/AGENTS.md"
  link_file "$SCRIPT_DIR/agent/AGENTS.md" "$HOME_DIR/.gemini/GEMINI.md"
  link_file "$SCRIPT_DIR/agent/agents" "$HOME_DIR/.claude/agents"
  link_file "$SCRIPT_DIR/agent/commands" "$HOME_DIR/.claude/commands"
  link_file "$SCRIPT_DIR/agent/commands" "$HOME_DIR/.codex/prompts"
  link_file "$SCRIPT_DIR/agent/settings.json" "$HOME_DIR/.claude/settings.json"
  link_file "$SCRIPT_DIR/agent/skills" "$HOME_DIR/.claude/skills"
  link_file "$SCRIPT_DIR/agent/skills" "$HOME_DIR/.codex/skills"
  if [ -e "$SCRIPT_DIR/agent/statusline-command.sh" ]; then
    link_file "$SCRIPT_DIR/agent/statusline-command.sh" "$HOME_DIR/.claude/statusline-command.sh"
  fi
}

main() {
  log "Docker dotfiles install"
  log "SCRIPT_DIR=$SCRIPT_DIR"
  log "HOME_DIR=$HOME_DIR"
  log "PREFIX=$PREFIX"
  log "BIN_DIR=$BIN_DIR"

  if ! need_cmd curl || ! need_cmd python3 || ! need_cmd tar; then
    warn "curl, python3, and tar are required for tool downloads"
  else
    install_zsh_userland
    install_gh
    install_starship
  fi

  write_docker_shell_bootstrap
  link_dotfiles
  install_tpm
  maybe_set_default_shell

  log "Install completed"
  log "Run: export PATH=\"$BIN_DIR:$HOME_DIR/bin:\$PATH\" && zsh"
}

main "$@"
