# ===== Global (共通) =====
format = """
$hostname
$directory\
$git_branch\
$git_status\
$cmd_duration\
$time
$character"""

[character]
format = "[⚡️](bold green) "
success_symbol = "[⚡️](bold green) "
error_symbol = "[⚡️](bold red) "

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"

[git_status]
disabled = true

[hostname]
disabled = false
ssh_only = false
format = "[$hostname]($style) "
style = "bold cyan"
trim_at = "."

[gcloud]
disabled = true

[time]
disabled = false
time_format = "%Y-%m-%d %H:%M"
utc_time_offset = "+9"

[username]
disabled = true

[cmd_duration]
min_time = 500
format = "[$duration]($style) "

[git_branch]
symbol = "🌱 "
truncation_length = 4
truncation_symbol = ""
