import assert from "node:assert/strict";
import childProcess from "node:child_process";
import { syncBuiltinESMExports } from "node:module";

const calls = [];
childProcess.execFile = (...args) => calls.push(args);
syncBuiltinESMExports();
process.env.AGENT_QUESTION_SOUND = "on";
delete process.env.ORCA_PI_STATUS_OWNED;
delete process.env.ORCA_PI_TITLE_MARKER_OWNED;
const { default: install } = await import("../pi-question-pop.ts");
const handlers = {};
install({ on: (event, handler) => { handlers[event] = handler; } });
const active = { hasUI: true, isIdle: () => false };
handlers.session_start({});
handlers.ui_prompt_start({}, active);
handlers.ui_prompt_start({}, active);
assert.equal(calls.length, 1);
assert.equal(calls[0][0], "/usr/bin/afplay");
handlers.session_start({});
handlers.ui_prompt_start({}, active);
assert.equal(calls.length, 2);
assert.equal(calls[1][0], "/usr/bin/afplay");
assert.equal(handlers.agent_end, undefined);
assert.equal(handlers.agent_settled, undefined);
handlers.ui_prompt_end({});
handlers.ui_prompt_start({}, { hasUI: false, isIdle: () => false });
assert.equal(calls.length, 2);
handlers.ui_prompt_end({});
handlers.ui_prompt_start({}, { hasUI: true, isIdle: () => true });
assert.equal(calls.length, 2);
handlers.ui_prompt_end({});
const originalKill = process.kill;
process.kill = () => {};
process.env.ORCA_PI_STATUS_OWNED = "1234";
handlers.ui_prompt_start({}, active);
assert.equal(calls.length, 2);
process.kill = originalKill;
delete process.env.ORCA_PI_STATUS_OWNED;
handlers.ui_prompt_end({});
process.env.AGENT_QUESTION_SOUND = "off";
handlers.ui_prompt_start({}, active);
assert.equal(calls.length, 2);
console.log("pi prompt event tests passed");
